export const componentMapping = {
  color: [
    { label: "Rouge", color: "red" },
    { label: "Bleu", color: "blue" },
    { label: "Noir", color: "black" },
    { label: "Blanc", color: "white" },
    { label: "Jaune", color: "yellow" },
  ],
  texture: [
    { label: "Texture", uiPath: "./img/button/test-1.png", modelPath: "" },
    { label: "Texture", uiPath: "./img/button/test-1.png", modelPath: "" },
    { label: "Texture", uiPath: "./img/button/test-1.png", modelPath: "" },
  ],
  tableau: [
    {
      label: "Tableau",
      uiPath: "./img/choice/texture.svg",
      modelPath: "/src/assets/walls/paintings/tableau-test.glb",
      texture: "/src/assets/walls/paintings/textures/pay-picture1.jpg",
      orientation: "paysage",
      sizes: [1, 1, 1],
    },
    {
      label: "Tableau",
      uiPath: "./img/choice/texture.svg",
      modelPath: "/src/assets/walls/paintings/tableau-test.glb",
      texture: "/src/assets/walls/paintings/textures/pay-picture2.jpg",
      orientation: "paysage",
      sizes: [1, 1, 1],
    },
    {
      label: "Tableau",
      uiPath: "./img/choice/texture.svg",
      modelPath: "/src/assets/walls/paintings/tableau-test.glb",
      texture: "/src/assets/walls/paintings/textures/pay-picture4.jpg",
      orientation: "paysage",
      sizes: [1, 1, 1],
    },
    {
      label: "Tableau",
      uiPath: "./img/choice/texture.svg",
      modelPath: "/src/assets/walls/paintings/tableau-test.glb",
      texture: "/src/assets/walls/paintings/textures/pay-picture5.jpg",
      orientation: "paysage",
      sizes: [1, 1, 1],
    },
    {
      label: "Tableau",
      uiPath: "./img/choice/texture.svg",
      modelPath: "/src/assets/walls/paintings/tableau-test.glb",
      texture: "/src/assets/walls/paintings/textures/pay-picture6.jpg",
      orientation: "paysage",
      sizes: [1, 1, 1],
    },
    {
      label: "Tableau",
      uiPath: "./img/choice/texture.svg",
      modelPath: "/src/assets/walls/paintings/tableau-test.glb",
      texture: "/src/assets/walls/paintings/textures/pay-picture9.jpg",
      orientation: "paysage",
      sizes: [1, 1, 1],
    },
    {
      label: "Tableau",
      uiPath: "./img/choice/texture.svg",
      modelPath: "/src/assets/walls/paintings/tableau-test.glb",
      texture: "/src/assets/walls/paintings/textures/pay-picture10.jpg",
      orientation: "paysage",
      sizes: [1, 1, 1],
    },
    {
      label: "Tableau",
      uiPath: "./img/choice/texture.svg",
      modelPath: "/src/assets/walls/paintings/tableau-test.glb",
      texture: "/src/assets/walls/paintings/textures/pay-picture11.jpg",
      orientation: "paysage",
      sizes: [1, 1, 1],
    },
    {
      label: "Tableau",
      uiPath: "./img/choice/texture.svg",
      modelPath: "/src/assets/walls/paintings/tableau-test.glb",
      texture: "/src/assets/walls/paintings/textures/por-picture3.jpg",
      orientation: "portait",
      sizes: [1, 1, 1],
    },
    {
      label: "Tableau",
      uiPath: "./img/choice/texture.svg",
      modelPath: "/src/assets/walls/paintings/tableau-test.glb",
      texture: "/src/assets/walls/paintings/textures/por-picture7.jpg",
      orientation: "portait",
      sizes: [1, 1, 1],
    },
    {
      label: "Tableau",
      uiPath: "./img/choice/texture.svg",
      modelPath: "/src/assets/walls/paintings/tableau-test.glb",
      texture: "/src/assets/walls/paintings/textures/por-picture8.jpg",
      orientation: "portait",
      sizes: [1, 1, 1],
    },
  ],
  statue: [
    {
      label: "Statue",
      uiPath: "./img/choice/texture.svg",
      modelPath: "/src/assets/floor/statues/statue_1.glb",
      sizes: [1, 1, 1],
    },
    {
      label: "Statue",
      uiPath: "./img/choice/texture.svg",
      modelPath: "/src/assets/floor/statues/statue_2.glb",
      sizes: [1, 1, 1],
    },
    {
      label: "Statue",
      uiPath: "./img/choice/texture.svg",
      modelPath: "/src/assets/floor/statues/statue_3.glb",
      sizes: [1, 1, 1],
    },
    {
      label: "Statue",
      uiPath: "./img/choice/texture.svg",
      modelPath: "/src/assets/floor/statues/statue_4.glb",
      sizes: [1, 1, 1],
    },
    {
      label: "Statue",
      uiPath: "./img/choice/texture.svg",
      modelPath: "/src/assets/floor/statues/statue_5.glb",
      sizes: [1, 1, 1],
    },
  ],
  furniture: [
    {
      label: "Sofa",
      uiPath: "./img/choice/texture.svg",
      modelPath: "/src/assets/floor/furnitures/furniture_1.glb",
      sizes: [1, 1, 1],
    },
    {
      label: "Sofa",
      uiPath: "./img/choice/texture.svg",
      modelPath: "/src/assets/floor/furnitures/furniture_2.glb",
      sizes: [1, 1, 1],
    },
    {
      label: "Sofa",
      uiPath: "./img/choice/texture.svg",
      modelPath: "/src/assets/floor/furnitures/furniture_3.glb",
      sizes: [1, 1, 1],
    },
    {
      label: "Sofa",
      uiPath: "./img/choice/texture.svg",
      modelPath: "/src/assets/floor/furnitures/furniture_4.glb",
      sizes: [1, 1, 1],
    },
    {
      label: "Sofa",
      uiPath: "./img/choice/texture.svg",
      modelPath: "/src/assets/floor/furnitures/furniture_5.glb",
      sizes: [1, 1, 1],
    },
  ],
  decoration: [
    {
      label: "Plante",
      uiPath: "./img/choice/texture.svg",
      modelPath: "/src/assets/floor/decorations/plante_1.glb",
      sizes: [1, 1, 1],
    },
    {
      label: "Plante",
      uiPath: "./img/choice/texture.svg",
      modelPath: "/src/assets/floor/decorations/plante_2.glb",
      sizes: [1, 1, 1],
    },
    {
      label: "Plante",
      uiPath: "./img/choice/texture.svg",
      modelPath: "/src/assets/floor/decorations/plante_3.glb",
      sizes: [1, 1, 1],
    },
    {
      label: "Plante",
      uiPath: "./img/choice/texture.svg",
      modelPath: "/src/assets/floor/decorations/plante_4.glb",
      sizes: [1, 1, 1],
    },
    {
      label: "Plante",
      uiPath: "./img/choice/texture.svg",
      modelPath: "/src/assets/floor/decorations/plante_5.glb",
      sizes: [1, 1, 1],
    },
  ],
};
