export const componentMapping = {
  color: [
    { label: "Vert pistache", color: "#d8eca6" },
    { label: "Gris mauve", color: "#c7c1bf" },
    { label: "Rouge framboise", color: "#9c494a" },
    { label: "Rose orange", color: "#ffd5b9" },
    { label: "Jaune crème", color: "#fff5d5" },
    { label: "Marron pourpre", color: "#702d1d" },
    { label: "Blanc", color: "#e7ddd6" },
    { label: "Beige pâle", color: "#cdb98e" },
    // Sol
    { label: "Orange", color: "#ff812c" },
    { label: "Jaune foncé", color: "#cda449" },
    { label: "Marron crème", color: "#9d7a60" },
    { label: "Bleu nuit d'été", color: "#d5deff" },
    { label: "Bleu clair", color: "#b9e3ff" },
    { label: "Bleu mauve", color: "#6564b7" },
    { label: "Bleu gris", color: "#718b9c" },
    { label: "Pourpre", color: "#af2f47" },
  ],
  tableau: [
    {
      id: 0,
      label:
        "Arrivée et interrogatoire des galériens dans la prison de Gênes - Galériens en prison",
      uiPath: "/assets/walls/paintings/textures/pay-picture1.jpg",
      modelPath: "/assets/walls/paintings/paysage-cadre.glb",
      texture: "/assets/walls/paintings/textures/pay-picture1.jpg",
      orientation: "paysage",
      sizes: [3, 3, 3],
    },
    {
      id: 1,
      label: "La Chasse aux renards",
      uiPath: "/assets/walls/paintings/textures/pay-picture2.jpg",
      modelPath: "/assets/walls/paintings/paysage-cadre.glb",
      texture: "/assets/walls/paintings/textures/pay-picture2.jpg",
      orientation: "paysage",
      sizes: [3, 3, 3],
    },
    {
      id: 2,
      label: "Le Triomphe de Silène",
      uiPath: "/assets/walls/paintings/textures/pay-picture4.jpg",
      modelPath: "/assets/walls/paintings/paysage-cadre.glb",
      texture: "/assets/walls/paintings/textures/pay-picture4.jpg",
      orientation: "paysage",
      sizes: [3, 3, 3],
    },
    {
      id: 3,
      label: "Les Beaux-Arts",
      uiPath: "/assets/walls/paintings/textures/pay-picture5.jpg",
      modelPath: "/assets/walls/paintings/paysage-cadre.glb",
      texture: "/assets/walls/paintings/textures/pay-picture5.jpg",
      orientation: "paysage",
      sizes: [3, 3, 3],
    },
    {
      id: 4,
      label: "Phèdre et Hippolyte",
      uiPath: "/assets/walls/paintings/textures/pay-picture6.jpg",
      modelPath: "/assets/walls/paintings/paysage-cadre.glb",
      texture: "/assets/walls/paintings/textures/pay-picture6.jpg",
      orientation: "paysage",
      sizes: [3, 3, 3],
    },
    {
      id: 5,
      label:
        "Réception de l'ambassadeur de France, le vicomte d'Andrezel, par le sultan Ahmed III, le 17 octobre 1724, à Constantinople l'audience du Sultan",
      uiPath: "/assets/walls/paintings/textures/pay-picture9.jpg",
      modelPath: "/assets/walls/paintings/paysage-cadre.glb",
      texture: "/assets/walls/paintings/textures/pay-picture9.jpg",
      orientation: "paysage",
      sizes: [3, 3, 3],
    },
    {
      id: 6,
      label:
        "Réception de l'ambassadeur de France, le vicomte d'Andrezel, par le sultan Ahmed III, le 17 octobre 1724, à Constantinople le dîner offert par le grand vizir Ibrahim Pacha",
      uiPath: "/assets/walls/paintings/textures/pay-picture10.jpg",
      modelPath: "/assets/walls/paintings/paysage-cadre.glb",
      texture: "/assets/walls/paintings/textures/pay-picture10.jpg",
      orientation: "paysage",
      sizes: [3, 3, 3],
    },
    {
      id: 7,
      label:
        "Une vieille femme défendant son étal de fruits à un jeune chapardeur - Marchande de fruits ou vieille femme gardant ses fruits contre un enfant",
      uiPath: "/assets/walls/paintings/textures/pay-picture11.jpg",
      modelPath: "/assets/walls/paintings/paysage-cadre.glb",
      texture: "/assets/walls/paintings/textures/pay-picture11.jpg",
      orientation: "paysage",
      sizes: [3, 3, 3],
    },
    {
      id: 8,
      label:
        "La Vision de sainte Catherine de Sienne - Allégorie à la Religion - Allégorie dont le sujet paraît être la Sainte Epine",
      uiPath: "/assets/walls/paintings/textures/por-picture3.jpg",
      modelPath: "/assets/walls/paintings/portrait-cadre.glb",
      texture: "/assets/walls/paintings/textures/por-picture3.jpg",
      orientation: "portrait",
      sizes: [3, 3, 3],
    },
    {
      id: 9,
      label:
        "Portrait de la princesse Frédérique Louise Wilhelmine d'Orange-Nassau - Frédérique Louise Wilhelmine, princesse d'Orange- Nassau",
      uiPath: "/assets/walls/paintings/textures/por-picture7.jpg",
      modelPath: "/assets/walls/paintings/portrait-cadre.glb",
      texture: "/assets/walls/paintings/textures/por-picture7.jpg",
      orientation: "portrait",
      sizes: [3, 3, 3],
    },
    {
      id: 10,
      label: "Portraits supposés de Mesdames Tallien et Récamier",
      uiPath: "/assets/walls/paintings/textures/por-picture8.jpg",
      modelPath: "/assets/walls/paintings/portrait-cadre.glb",
      texture: "/assets/walls/paintings/textures/por-picture8.jpg",
      orientation: "portrait",
      sizes: [3, 3, 3],
    },
  ],
  statue: [
    {
      id: 11,
      label: "Statue 1",
      uiPath: "/assets/floor/statues/statue_1.png",
      modelPath: "/assets/floor/statues/statue_1.glb",
      sizes: [0.897, 0.803, 3.17],
    },
    {
      id: 12,
      label: "Statue 2",
      uiPath: "/assets/floor/statues/statue_2.png",
      modelPath: "/assets/floor/statues/statue_2.glb",
      sizes: [1.21, 0.719, 3.17],
    },
    {
      id: 13,
      label: "Statue 3",
      uiPath: "/assets/floor/statues/statue_3.png",
      modelPath: "/assets/floor/statues/statue_3.glb",
      sizes: [1.98, 1.31, 4.01],
    },
    {
      id: 14,
      label: "Statue 4",
      uiPath: "/assets/floor/statues/statue_4.png",
      modelPath: "/assets/floor/statues/statue_4.glb",
      sizes: [1.02, 0.869, 3.16],
    },
    {
      id: 15,
      label: "Statue 5",
      uiPath: "/assets/floor/statues/statue_5.png",
      modelPath: "/assets/floor/statues/statue_5.glb",
      sizes: [1.51, 1.19, 4.4],
    },
  ],
  furniture: [
    {
      id: 16,
      label: "Canapé bleu",
      uiPath: "/assets/floor/furnitures/furniture_1.png",
      modelPath: "/assets/floor/furnitures/furniture_1.glb",
      sizes: [4.68, 2.06, 1.58],
    },
    {
      id: 17,
      label: "Banc",
      uiPath: "/assets/floor/furnitures/furniture_2.png",
      modelPath: "/assets/floor/furnitures/furniture_2.glb",
      sizes: [3, 1.04, 0.711],
    },
    {
      id: 18,
      label: "Chaise",
      uiPath: "/assets/floor/furnitures/furniture_3.png",
      modelPath: "/assets/floor/furnitures/furniture_3.glb",
      sizes: [0.884, 1.01, 1.5],
    },
    {
      id: 19,
      label: "Sofa rouge",
      uiPath: "/assets/floor/furnitures/furniture_4.png",
      modelPath: "/assets/floor/furnitures/furniture_4.glb",
      sizes: [2.43, 2.26, 1.27],
    },
    {
      id: 20,
      label: "Pouf bleu",
      uiPath: "/assets/floor/furnitures/furniture_5.png",
      modelPath: "/assets/floor/furnitures/furniture_5.glb",
      sizes: [2.02, 2.01, 1.06],
    },
  ],
  decoration: [
    {
      id: 21,
      label: "Plante 1",
      uiPath: "/assets/floor/flowers/plante_1.png",
      modelPath: "/assets/floor/flowers/plante_1.glb",
      sizes: [1.44, 1.27, 2],
    },
    {
      id: 22,
      label: "Plante 2",
      uiPath: "/assets/floor/flowers/plante_2.png",
      modelPath: "/assets/floor/flowers/plante_2.glb",
      sizes: [1.18, 1.19, 1.98],
    },
    {
      id: 23,
      label: "Plante 3",
      uiPath: "/assets/floor/flowers/plante_3.png",
      modelPath: "/assets/floor/flowers/plante_3.glb",
      sizes: [1.68, 1.62, 1.99],
    },
    {
      id: 24,
      label: "Plante 4",
      uiPath: "/assets/floor/flowers/plante_4.png",
      modelPath: "/assets/floor/flowers/plante_4.glb",
      sizes: [1.64, 1.6, 2.43],
    },
    {
      id: 25,
      label: "Plante 5",
      uiPath: "/assets/floor/flowers/plante_5.png",
      modelPath: "/assets/floor/flowers/plante_5.glb",
      sizes: [1.86, 1.87, 1.71],
    },
  ],
};
